# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '079888673860.dkr.ecr.ap-south-1.amazonaws.com/in-dev-platform'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 079888673860.dkr.ecr.ap-south-1.amazonaws.com
          docker tag in-dev-platform:latest 079888673860.dkr.ecr.ap-south-1.amazonaws.com/in-dev-platform:latest
          docker push 079888673860.dkr.ecr.ap-south-1.amazonaws.com/in-dev-platform:latest